name: CI

on:
  push:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@v3
    -
      name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: pcov
    -
      name: Install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
    -
      name: Run test suite
      run: composer test
    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./vendor/bin/php-coveralls --coverage_clover=./coverage/clover.xml --json_path=./coverage/lcov.info
    # -
    #   name: Coveralls
    #   uses: coverallsapp/github-action@1.1.3
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
